### ISSUE TITLE
Fehlende Icons Mehr-Bereich

### ISSUE THREAD

**Issue by dkompakt** [efechq/dkissues#11]
Im Mehr-Bereich fehlen noch Icons, das sollten diese hier sein (siehe DK App > Ressourcen > Icons):

- Mein Profil = “002-user”
- Datenschutz = “004-protection”
- Impressum = “005-document”
- Inhalte löschen = “003-delete”
- Logout = “001-logout”

**Comment by jowe13** [comment]
done
