### ISSUE TITLE
Post-Log-out-Screen

### ISSUE THREAD

**Issue by dkompakt** [efechq/dkissues#14]
Nachdem ich mich ausgeloggt habe, bekomme ich einen Screen, wo ich zu den AGBs zustimmen soll. DAs macht ja keinen Sinn, dass man bei jedem Login wieder den AGBs zustimmen muss. Ich würde stattdessen einen Screen vorsehen, wo oben ein Button "EInloggen" steht und unten einer mit "Registrieren". 

"Einloggen" dann weiß mit #ce0071 als Schriftfarbe und "Registrieren" mit weißem rahmen und weißer Schrift und den Inhalt des Buttons dann in #ce0071

**Comment by jowe13** [comment]
mit neuem login flow behoben
