### ISSUE TITLE
Abfrage Onboarding

### ISSUE THREAD

**Issue by dkompakt** [efechq/dkissues#4]
Beim Onboarding fragen wir mehrere Punkte ab und bei einem Thema kommt eine Drop-down-Liste, wo nur Items stehen. Wir wollten dort glaube ich das Unternehmen abfragen. Also statt Drop-down lieber ein Textfeld anwenden und die NutzerInnen können dann ihren Firmennamen eintragen

**Comment by jowe13** [comment]
done
