### ISSUE TITLE
Drop-downs Onboarding

### ISSUE THREAD

**Issue by dkompakt** [efechq/dkissues#5]
Im Onboarding sind die Drop-downs teilweise buggy. Obwohl man auf ein Element klickt, schließt sich das Drop-down nicht. Wenn ich ein Element klicke. sollte sich das Drop-down schließen und ich zum nächsten geführt werden.

**Comment by jowe13** [comment]
Ist ja nur noch eins.

Macht relativ wenig Sinn. Ich müsste direkt beim Scrollen auf dem richtigen landen. Wenn ich das nicht tue geht der Picker zu. Das wäre doof
