### ISSUE TITLE
Beantwortete Umfragen

### ISSUE THREAD

**Issue by dkompakt** [efechq/dkissues#7]
Können wir eine Umfrage aus dem Stream des Nutzers nehmen lassen, wenn er dort einmal eine Antwort gegeben hat? Es muss ja nicht sein, dass dort immer ein Frage steht, die man schon beantwortet hat

Zum Beispiel auch bei der Umfrage “Welches Format hörst du …”: Nach dem Absenden der Frage steht mein Format noch sichtbar im Feld. Es wird nicht deutlich, dass das Absenden geklappt hat. Vielleicht ein kleines Herz oder auch Danke aufploppen lassen?

**Comment by jowe13** [comment]
done
